### PR TITLE
Added Landing page

### PR DESCRIPTION
**Pull request by sainath7878**
Added landing page and made few changes to components. Let me know if any changes are to be made.

### CODE REVIEW

**Review by vrinda-mahajan — APPROVED** [review]
LGTM👍

**Comment by ApurvaSawant11** [comment]
I saw `Home` button on `index.html` page. You don't need a Home button when you are already on Home page. Rest everything looks good to me.

**Review by anik31 — APPROVED** [review]
Looks good

**Review by ParthParolekar — APPROVED** [review]
image

These two buttons get stacked up when the width is around 600px to 750px.

Everything else is great. Approved!

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me.

**Comment by sainath7878** [comment]
> image
> 
> These two buttons get stacked up when the width is around 600px to 750px.
> 
> Everything else is great. Approved!

Yeah, fixed that. Thanks for pointing out.

**Comment by sainath7878** [comment]
> I saw `Home` button on `index.html` page. You don't need a Home button when you are already on Home page. Rest everything looks good to me.

So should I remove the home button in index.html and the same way remove docs button from docs.html?

**Pull request merged**
